name: Pack NexusExtensions.Security

on:
  workflow_dispatch :
  pull_request:
    branches: [ main ]
    types: [closed]

defaults:
  run:
    working-directory: ./src/NexusExtensions.Security

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y.%m.%d.%H%M')"
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Pack
      run: dotnet pack -c Release -p:PackageVersion=${{ steps.date.outputs.date }} -o out
      
    - name: Add private GitHub registry to NuGet
      run: nuget sources add -name "NexusNugets" -Source https://nuget.pkg.github.com/Nexusmeister/index.json -Username Nexusmeister -Password ${{ secrets.GITHUB_TOKEN }}
        
    - name: Push generated package to GitHub registry
      run: nuget push ./out/*.nupkg -Source "NexusNugets" -SkipDuplicate

